// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProductLaunch.EndToEndTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Prospect Sign Up")]
    public partial class ProspectSignUpFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ProspectSignUp.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "Prospect Sign Up", "\tAs a prospect interested in the product launch\r\n\tI want to sign up for notificat" +
                    "ions\r\n\tSo that I can be updated with news", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sign Up with Valid Details")]
        [NUnit.Framework.TestCaseAttribute("Prospect", "A", "a.prospect@company.com", "Company, Inc.", "United States", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "B", "b.prospect@company.com", "Company, Inc.", "United Kingdom", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "C", "c.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "D", "d.prospect@company.com", "Company, Inc.", "United Kingdom", "IT Ops", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "E", "e.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "F", "f.prospect@other.com", "Other, Inc.", "Sweden", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "G", "g.prospect@company.com", "Company, Inc.", "United States", "Engineer", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "H", "h.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "I", "i.prospect@company.com", "Company, Inc.", "United Kingdom", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "J", "j.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "K", "k.prospect@other.com", "Other, Inc.", "Sweden", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "L", "l.prospect@company.com", "Company, Inc.", "United Kingdom", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "M", "m.prospect@company.com", "Company, Inc.", "Sweden", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "N", "n.prospect@company.com", "Company, Inc.", "United Kingdom", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "O", "o.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "P", "p.prospect@other.com", "Other, Inc.", "Sweden", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "Q", "q.prospect@other.com", "Other, Inc.", "Sweden", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "R", "r.prospect@company.com", "Company, Inc.", "United Kingdom", "IT Ops", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "S", "s.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "T", "t.prospect@company.com", "Company, Inc.", "United Kingdom", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "U", "u.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "V", "v.prospect@other.com", "Other, Inc.", "Sweden", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "W", "w.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "X", "x.prospect@company.com", "Company, Inc.", "United Kingdom", "Decision Maker", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "Y", "y.prospect@company.com", "Company, Inc.", "United States", "Architect", null)]
        [NUnit.Framework.TestCaseAttribute("Prospect", "Z", "z.prospect@other.com", "Other, Inc.", "Sweden", "Decision Maker", null)]
        public void SignUpWithValidDetails(string firstName, string lastName, string emailAddress, string companyName, string country, string role, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("EmailAddress", emailAddress);
            argumentsOfScenario.Add("CompanyName", companyName);
            argumentsOfScenario.Add("Country", country);
            argumentsOfScenario.Add("Role", role);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sign Up with Valid Details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given("I browse to the Sign Up Page at \"localhost:57120\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And(string.Format("I enter details \'{0}\' \'{1}\' \'{2}\' \'{3}\' \'{4}\' \'{5}\'", firstName, lastName, emailAddress, companyName, country, role), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
 testRunner.When("I press Go", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
 testRunner.Then("I should see the Thank You page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
